Add a mechanism to retrieve the API Gateway details
I've chosen a very verbose file name for the auto-generated file so that
if it's missing, the TypeScript build error tells you how to fix the
problem

If you have a clean git checkout and run npm run build you'll get:

> src/environment.ts:1:15 - error TS2307: Cannot find module './this-file-is-generated-by-running-npm-run-update-environment' or its corresponding type declarations.
>
> 1 export * from './this-file-is-generated-by-running-npm-run-update-environment';
                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~